#if DEBUG

using UnityEngine;

namespace PvZHelper.Behaviors;
internal class SeedTypeLoader : MonoBehaviour
{
    private void Start()
    {
        var json = Resources.Load<TextAsset>("LawnStrings").text;
        var plants = JsonUtility.FromJson<AlmanacMgr.PlantData>(json).plants;

        List<string> seedNames = [];
        for (int i = 0; i < GameAPP.plantPrefab.Length; i++)
        {
            var plant = GameAPP.plantPrefab[i];
            if (plant == null) continue;

            var name = plants.FirstOrDefault(p => p.seedType == i)?.name ?? plant.name;

            seedNames.Add($"{name} = {i},");
        }

        var codes = $$"""
        // <auto-generated/>
        namespace PvZHelper;

        internal enum SeedType : ushort
        {
        {{string.Join("\n", seedNames)}}
        }
        
        """;

        try
        {
            File.WriteAllText(@"E:\OneDrive\PartTime\Code\PvZHelper\PvZHelper\SeedType.cs", codes);
        }
        catch { }
    }
}
#endif